export enum AccountRole {
  ADMINISTRATOR = 'ADMINISTRATOR',
  HOTEL_MANAGER = 'HOTEL_MANAGER',
  RECEPTIONIST = 'RECEPTIONIST',
  HOUSEKEEPING_STAFF = 'HOUSEKEEPING_STAFF',
  MAINTENANCE_STAFF = 'MAINTENANCE_STAFF',
  CUSTOMER = 'CUSTOMER',
}
